name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - run: |
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/horta/zlib.install/master/install.bat -OutFile install_zlib.bat
        ./install_zlib.bat

    - name: Configure CMake
      run: |
        cmake -B ${{ github.workspace }}/build -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/mingw-w64-x86_64.cmake

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: pkg_pfs_tool
        path: build/pkg_pfs_tool
        if-no-files-found: error

