name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install \
        libmbedtls-dev \
        uthash-dev \
        zlib1g-dev \
        libz-mingw-w64-dev

    - name: Configure CMake
      run: |
        cmake -B $(pwd)/build
    - name: Build
      run: cmake --build $(pwd)/build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: pkg_pfs_tool
        path: build/pkg_pfs_tool
        if-no-files-found: error

