name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Configure CMake
      run: |
        cmake -B $(pwd)/build

    - name: Build
      run: cmake --build $(pwd)/build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: pkg_pfs_tool
        path: build/pkg_pfs_tool
        if-no-files-found: error

